name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - name: Write TMDB_KEY to .env
      run: echo 'TMDB_KEY={{ secrets.TMDB_KEY }}' > .env
    - name: Get packages
      run: flutter pub get
    - name: Run code generator
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - name: Run tests
      run: flutter test